# Generated by Django 4.2.1 on 2025-06-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_managers_alter_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_images/')),
                ('item_code', models.CharField(max_length=255, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('standard', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('lowest_stock', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('storing_place', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
