# Generated by Django 4.2.1 on 2025-07-13 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='factories',
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', '主任管理者'), ('assistant', '副管理者'), ('supervisor', '監督者')], default='primary', help_text='管理者の役割', max_length=255)),
                ('permissions', models.JSONField(default=dict, help_text='権限設定')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='任命日時')),
                ('is_active', models.BooleanField(default=True, help_text='有効/無効')),
                ('memo', models.TextField(blank=True, help_text='メモ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(help_text='管理対象工場', on_delete=django.db.models.deletion.CASCADE, to='api.factory')),
                ('user', models.ForeignKey(help_text='管理者ユーザー', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工場管理者',
                'verbose_name_plural': '工場管理者',
                'unique_together': {('user', 'factory')},
            },
        ),
    ]
