# Generated by Django 4.2.1 on 2025-07-15 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_account_factories_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(help_text='倉庫名', max_length=255)),
                ('description', models.TextField(blank=True, help_text='説明', null=True)),
                ('width', models.IntegerField(default=10, help_text='マップ横幅（グリッド単位）')),
                ('height', models.IntegerField(default=10, help_text='マップ縦幅（グリッド単位）')),
                ('status', models.CharField(choices=[('active', '稼働中'), ('inactive', '停止中'), ('maintenance', 'メンテナンス中')], default='active', help_text='倉庫ステータス', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(help_text='所属工場', on_delete=django.db.models.deletion.CASCADE, to='api.factory')),
            ],
            options={
                'verbose_name': '倉庫',
                'verbose_name_plural': '倉庫',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(help_text='置き場名', max_length=255)),
                ('x_position', models.IntegerField(help_text='X座標（グリッド単位）')),
                ('y_position', models.IntegerField(help_text='Y座標（グリッド単位）')),
                ('width', models.IntegerField(default=1, help_text='置き場の横幅（グリッド単位）')),
                ('height', models.IntegerField(default=1, help_text='置き場の縦幅（グリッド単位）')),
                ('capacity', models.IntegerField(default=100, help_text='収容能力')),
                ('current_stock', models.IntegerField(default=0, help_text='現在の在庫数')),
                ('location_type', models.CharField(choices=[('shelf', '棚'), ('floor', '床置き'), ('rack', 'ラック'), ('container', 'コンテナ')], default='shelf', help_text='置き場タイプ', max_length=255)),
                ('status', models.CharField(choices=[('available', '利用可能'), ('occupied', '使用中'), ('maintenance', 'メンテナンス中'), ('reserved', '予約済み')], default='available', help_text='置き場ステータス', max_length=255)),
                ('memo', models.TextField(blank=True, help_text='メモ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(help_text='所属倉庫', on_delete=django.db.models.deletion.CASCADE, to='api.warehouse')),
            ],
            options={
                'verbose_name': '置き場',
                'verbose_name_plural': '置き場',
                'unique_together': {('warehouse', 'x_position', 'y_position')},
            },
        ),
    ]
