# Generated by Django 4.2.1 on 2025-06-14 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_factory_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktaking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theoretical_stock', models.IntegerField(default=0)),
                ('actual_stock', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=255)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
