# Generated by Django 4.2.1 on 2025-07-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_warehouse_storagelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='location_type',
            field=models.CharField(choices=[('entrance', '入口'), ('square', '置き場四角'), ('circle', '置き場丸'), ('l_shape', '置き場L字'), ('u_shape', '置き場コの字')], default='square', help_text='置き場タイプ', max_length=255),
        ),
    ]
