# Generated by Django 4.2.1 on 2025-06-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stocktaking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='manager',
        ),
        migrations.AlterField(
            model_name='factory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(help_text='カテゴリ', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='作成日時'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, help_text='画像', null=True, upload_to='inventory_images/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_code',
            field=models.CharField(help_text='商品コード', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='lowest_stock',
            field=models.IntegerField(default=0, help_text='最低在庫数'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='memo',
            field=models.TextField(blank=True, help_text='メモ', null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(help_text='商品名', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='standard',
            field=models.CharField(blank=True, help_text='規格', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='在庫数'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='storing_place',
            field=models.CharField(blank=True, help_text='保管場所', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(help_text='単位', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='単価', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新日時'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'in'), ('out', 'out')], default='in', max_length=255),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
