# Generated by Django 4.2.1 on 2025-07-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_storagelocation_location_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'verbose_name': '置き場（旧）', 'verbose_name_plural': '置き場（旧）'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='storing_place',
            field=models.CharField(blank=True, help_text='保管場所（旧システム互換）', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StorageArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(help_text='置き場名（A, B, C...）', max_length=1)),
                ('width', models.IntegerField(default=3, help_text='置き場の横幅（座標数）')),
                ('height', models.IntegerField(default=3, help_text='置き場の縦幅（座標数）')),
                ('description', models.TextField(blank=True, help_text='説明', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(help_text='所属工場', on_delete=django.db.models.deletion.CASCADE, to='api.factory')),
            ],
            options={
                'verbose_name': '置き場（新）',
                'verbose_name_plural': '置き場（新）',
                'unique_together': {('factory', 'area_name')},
            },
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_position', models.IntegerField(help_text='X座標（1, 2, 3...）')),
                ('y_position', models.IntegerField(help_text='Y座標（1, 2, 3...）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_area', models.ForeignKey(help_text='所属置き場', on_delete=django.db.models.deletion.CASCADE, to='api.storagearea')),
            ],
            options={
                'verbose_name': '座標',
                'verbose_name_plural': '座標',
                'unique_together': {('storage_area', 'x_position', 'y_position')},
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='coordinate',
            field=models.ForeignKey(blank=True, help_text='保管座標（新システム）', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coordinate'),
        ),
    ]
