# Generated by Django 4.2.1 on 2025-07-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_storagelocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.CharField(blank=True, help_text='発注先', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SelectionOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_type', models.CharField(choices=[('category', 'カテゴリー'), ('supplier', '発注先'), ('unit', '単位')], help_text='選択肢の種類', max_length=50)),
                ('value', models.CharField(help_text='選択肢の値', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='有効/無効')),
                ('sort_order', models.IntegerField(default=0, help_text='表示順序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '選択肢',
                'verbose_name_plural': '選択肢',
                'ordering': ['option_type', 'sort_order', 'value'],
                'unique_together': {('option_type', 'value')},
            },
        ),
    ]
