# Generated by Django 4.2.1 on 2025-07-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_inventory_supplier_selectionoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectionOption',
        ),
    ]
